version: "3.7"

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: app
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "4306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: on-failure
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
